In [1]:
import psycopg2

# Define connection parameters
conn_params = {
    "host": "localhost",  # Database host
    "port": "5432",       # Port number, default is 5432
    "database": "dsp_project",  # Database name
    "user": "postgres",           # Username
    "password": "root"        # Password
}

In [ ]:
import psycopg2

# Define connection parameters
conn_params = {
    "host": "localhost",  # Database host
    "port": "5432",       # Port number, default is 5432
    "database": "dsp_project",  # Database name
    "user": "postgres",           # Username
    "password": "root"        # Password
}


# Establish the connection
try:
    # Connect to PostgreSQL
    connection = psycopg2.connect(**conn_params)
    cursor = connection.cursor()
    
    # SQL command to create the table 
    create_table_query = ''' CREATE TABLE IF NOT EXISTS transactions_details (
        id SERIAL PRIMARY KEY,
        trans_date_trans_time    TIMESTAMP NOT NULL,
        cc_num                   BIGINT NOT NULL,
        merchant                 TEXT NOT NULL,
        category                 TEXT NOT NULL,
        amt                      FLOAT8 NOT NULL,
        first                    TEXT NOT NULL,
        last                     TEXT NOT NULL,
        gender                   TEXT NOT NULL,
        street                   TEXT NOT NULL,
        city                     TEXT NOT NULL,
        state                    TEXT NOT NULL,
        zip                      INT NOT NULL,
        lat                      FLOAT8 NOT NULL,
        long                     FLOAT8 NOT NULL,
        city_pop                 INT NOT NULL,
        job                      TEXT NOT NULL,
        dob                      DATE NOT NULL,
        trans_num                TEXT NOT NULL,
        unix_time                BIGINT NOT NULL,
        merch_lat                FLOAT8 NOT NULL,
        merch_long               FLOAT8 NOT NULL,
        is_fraud                 INT NOT NULL
    );

    CREATE TABLE IF NOT EXISTS predict_table (
        id SERIAL PRIMARY KEY,
        merchant      TEXT NOT NULL,
        category      TEXT NOT NULL,
        amt           FLOAT8 NOT NULL,
        gender        TEXT NOT NULL,
        lat           FLOAT8 NOT NULL,
        long          FLOAT8 NOT NULL,
        city_pop      INT NOT NULL,
        job           TEXT NOT NULL,
        unix_time     BIGINT NOT NULL,
        merch_lat     FLOAT8 NOT NULL,
        merch_long    FLOAT8 NOT NULL,
        trans_date_trans_time    TIMESTAMP NOT NULL,
        is_fraud      INT NOT NULL
    );'''
    # Execute the SQL command
    cursor.execute(create_table_query)
    connection.commit()
    print('table created successfully')
    
except Exception as error:
    print("Error ", error)

finally:
    # Close the connection
    if connection:
        cursor.close()
        connection.close()
        print("PostgreSQL connection is closed")

In [2]:
import psycopg2

# Define connection parameters
conn_params = {
    "host": "localhost",  # Database host
    "port": "5432",       # Port number, default is 5432
    "database": "dsp_project",  # Database name
    "user": "postgres",           # Username
    "password": "root"        # Password
}


# Establish the connection
try:
    # Connect to PostgreSQL
    connection = psycopg2.connect(**conn_params)
    cursor = connection.cursor()
    
    # SQL command to create the table 
    create_table_query = ''' CREATE TABLE IF NOT EXISTS transactions_details (
        id SERIAL PRIMARY KEY,
        trans_date_trans_time    TIMESTAMP NOT NULL,
        cc_num                   BIGINT NOT NULL,
        merchant                 TEXT NOT NULL,
        category                 TEXT NOT NULL,
        amt                      FLOAT8 NOT NULL,
        first                    TEXT NOT NULL,
        last                     TEXT NOT NULL,
        gender                   TEXT NOT NULL,
        street                   TEXT NOT NULL,
        city                     TEXT NOT NULL,
        state                    TEXT NOT NULL,
        zip                      INT NOT NULL,
        lat                      FLOAT8 NOT NULL,
        long                     FLOAT8 NOT NULL,
        city_pop                 INT NOT NULL,
        job                      TEXT NOT NULL,
        dob                      DATE NOT NULL,
        trans_num                TEXT NOT NULL,
        unix_time                BIGINT NOT NULL,
        merch_lat                FLOAT8 NOT NULL,
        merch_long               FLOAT8 NOT NULL,
        is_fraud                 INT NOT NULL
    );

    CREATE TABLE IF NOT EXISTS predict_table (
        id SERIAL PRIMARY KEY,
        merchant      TEXT NOT NULL,
        category      TEXT NOT NULL,
        amt           FLOAT8 NOT NULL,
        gender        TEXT NOT NULL,
        lat           FLOAT8 NOT NULL,
        long          FLOAT8 NOT NULL,
        city_pop      INT NOT NULL,
        job           TEXT NOT NULL,
        unix_time     BIGINT NOT NULL,
        merch_lat     FLOAT8 NOT NULL,
        merch_long    FLOAT8 NOT NULL,
        trans_date_trans_time    TIMESTAMP NOT NULL,
        is_fraud      INT NOT NULL
    );'''
    # Execute the SQL command
    cursor.execute(create_table_query)
    connection.commit()
    print("Table 'transactions' created successfully in PostgreSQL")
     insert_query = '''INSERT INTO predict_table (merchant, category,amt,gender,lat,long,city_pop,job,unix_time,merch_lat,merch_long,trans_date_trans_time,is_fraud) 
        VALUES ('fraud_Rippin, Kub and Mann', 'misc_net', 4.97, 'F', 36.0788, -81.1781, 3495, 'Psychologist, counselling', 
                1325376018, 36.011293, -82.048315, 2020-12-30 06:23:47,0)'''
    cursor.execute(insert_query)
    connection.commit()
    print('Records are successfully inserted.')"""

    select_query = ''' SELECT * FROM predict_table'''
    cursor.execute(select_query)
    data_ = cursor.fetchall()

    print('Records:\n')
    for row in data_:
        print(row)
    
    
except Exception as error:
    print("Error ", error)

finally:
    # Close the connection
    if connection:
        cursor.close()
        connection.close()
        print("PostgreSQL connection is closed")

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

PostgreSQL connection is closed

In [1]:
import psycopg2
import pandas as pd

input_data = pd.DataFrame({
    'merchant': ['Merchant A'],
    'category': ['Category 1'],
    'amt': [100.50],
    'gender': ['M'],
    'lat': [40.7128],
    'long': [-74.0060],
    'city_pop': [8000000],
    'job': ['Engineer'],
    'unix_time': [1625097600],
    'merch_lat': [40.730610],
    'merch_long': [-73.935242],
    'is_fraud': [0]
})

# Define connection parameters
conn_params = {
    "host": "localhost",  # Database host
    "port": "5432",       # Port number, default is 5432
    "database": "dsp_project",  # Database name
    "user": "postgres",           # Username
    "password": "root"        # Password
}


# Establish the connection
try:
    # Connect to PostgreSQL
    connection = psycopg2.connect(**conn_params)
    cursor = connection.cursor()
    
    # SQL command to create the table 
    insert_query = '''
    INSERT INTO predict_table (merchant, category, amt, gender, lat, long, city_pop, job, unix_time, merch_lat, merch_long, is_fraud)
    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s);
    '''
    
    # Iterate over the DataFrame rows and insert each row into the database
    for index, row in input_data.iterrows():
        cursor.execute(insert_query, (
            row['merchant'], row['category'], row['amt'], row['gender'], 
            row['lat'], row['long'], row['city_pop'], row['job'], 
            row['unix_time'], row['merch_lat'], row['merch_long'], row['is_fraud']
        ))
    
    # Commit the transaction
    connection.commit()
    print("DataFrame inserted successfully into simple_transactions table")

    select_query = ''' SELECT * FROM predict_table WHERE is_fraud=1 LIMIT 10'''
    cursor.execute(select_query)
    data_ = cursor.fetchall()

    print('Records:\n')
    for row in data_:
        print(row)
    
    
except Exception as error:
    print("Error ", error)

finally:
    # Close the connection
    if connection:
        cursor.close()
        connection.close()
        print("PostgreSQL connection is closed")

ImportError: DLL load failed while importing _multiarray_umath: The specified module could not be found.

ImportError: DLL load failed while importing _multiarray_umath: The specified module could not be found.

DataFrame inserted successfully into simple_transactions table
Records:

(3, 'fraud_Rippin, Kub and Mann', 'misc_net', 0.0, 'M', 0.0, 0.0, 0, 'Psychologist, counselling', 0, 0.0, 0.0, 1)
(4, 'fraud_Kutch, Hermiston and Farrell', 'misc_net', 0.0, 'M', 0.0, 8.6e-06, 11, 'Psychologist, counselling', 0, 0.0, 0.0, 1)
(5, 'fraud_Rowe-Vandervort', 'misc_net', 0.0, 'M', 0.0, 8.6e-06, 11, 'Psychologist, counselling', 0, 0.0, 0.0, 1)
(64, 'fraud_Bauch-Blanda', 'entertainment', 121.46, 'F', 27.9004, -82.7152, 172247, 'Geneticist, molecular', 1371817956, 27.482301, -83.200829, 1)
(73, 'fraud_Ziemann-Waters', 'health_fitness', 181.87, 'F', 30.5354, -95.4532, 4993, 'Scientist, biomedical', 1371818047, 31.152375, -95.272196, 1)
(106, 'fraud_Greenholt Ltd', 'health_fitness', 242.35, 'F', 40.0897, -74.9781, 1526206, 'Commercial horticulturist', 1371818748, 39.151823, -75.035003, 1)
(107, 'fraud_Bahringer Group', 'health_fitness', 20.66, 'F', 41.4972, -98.7858, 509, "Nurse, children's", 1371818768, 41.103974, -98.4845, 1)
(139, 'fraud_Gislason Group', 'travel', 558.03, 'M', 30.251, -92.5002, 1261, 'Broadcast presenter', 1371819319, 30.87087, -92.873036, 1)
(173, 'fraud_Schumm PLC', 'shopping_net', 1199.45, 'F', 34.2651, -77.867, 186140, 'English as a second language teacher', 1371820126, 34.622777, -77.827863, 1)
(215, 'fraud_Romaguera, Wehner and Tromp', 'kids_pets', 79.56, 'F', 45.4963, -89.7273, 9594, 'Seismic interpreter', 1371821073, 46.117649, -90.18511, 1)
PostgreSQL connection is closed